[package]
name = "rustcastai"
version = "0.1.0"
description = "Wrapper around the Recast.AI API"
readme = "README.md"
license = "MIT"
authors = ["jhoudan <jerom.houdan@gmail.com>"]

[dependencies]
curs = "0.1.3"
reqwest = "*"
serde = "0.8"
serde_json = "0.8"
serde_derive = "0.8.17"
