[package]
name = "rustcastai"
version = "0.2.0"
description = "Wrapper around the Recast.AI API"
readme = "README.md"
license = "MIT"
authors = ["jhoudan <jerom.houdan@gmail.com>"]

[dependencies]
reqwest = "0.4"
serde = "0.9"
serde_json = "0.9"
serde_derive = "0.9"
